### ISSUE TITLE
Pull request disabled?

### ISSUE THREAD

**Issue by killerkalamari** [rigred/sandsifter-tests#3]
Can't create a branch, can't create a pull request:
![image](https://user-images.githubusercontent.com/5439104/30253201-42d2ba9e-9635-11e7-8ead-b1e861af2128.png)

**Comment by rigred** [comment]
It should work as normal. Nothing is disabled. https://help.github.com/articles/creating-a-pull-request/

I have created a new branch named `submissions` which you can try.

**Comment by zenware** [comment]
One thing that should be noted is that the branch you are trying to push from, and the branch you are trying to push too, ought to be different in order for that button to become enabled.

**Comment by killerkalamari** [comment]
I'm not sure how to create a branch on GitHub. I created one in git and tried to git push but got a 403.

**Comment by zenware** [comment]
You need to fork the project on GitHub which it seems you have done, and then on your localhost, what's the output of `git remote -v`?
It should be something like "https://github.com/killerkalamari/sandsifter-tests.git"
If it's different, then you can fix it by the following commands
```
git remote rename origin upstream
git remote add origin https://github.com/killerkalamari/sandsifter-tests.git
```
After which I'd probably git pull or git fetch just in case.
Then `git checkout -b <branch_name>` is the shortcut to create and switch to a new branch from the command line.
You could also do `git branch <branch_name>` and `git checkout <branch_name>`.
When you want to push your branch, git initially won't know exactly how. To remedy this, you can say `git push -u origin/<branch_name>`.
`git push -u` is shorthand for `git push --set-upstream` since the upstream branch, which in this case also happens to be the remote origin, doesn't know where to place the contents of a local branch unless you tell it. 

The usual flow is "rebase master onto your feature branch" and then "merge your feature into master." However in this case features are just some object artifact, so it's unlikely the problem which that workflow solves will come up.

I should also note that I think you misinterpreted what I originally said to mean, but that's because I wrote it ambiguously. What I meant was, 'the contents of each branch should differ' otherwise they are the same, and thus it makes no sense to merge them.

It would seem that you have pushed no commits to your fork of the repository so there's no reason a pull request should work. If you wish to update the contents of your repository with the newer contents in rigred's repository, as far as I'm aware the standard way to do that is to fetch his remote into your local and then push to your remote.

However, because you got the 403 forbidden I suspect the initial `git remote -v` will return "https://github.com/rigred/sandsifter-tests.git", and you got a forbidden request response because you are obviously not allowed to directly modify someone else's remote without their first giving explicit permission.

**Comment by rigred** [comment]
How is it going @killerkalamari ?

**Comment by killerkalamari** [comment]
"You need to fork the project on GitHub which it seems you have done"

^^^ Actually, the opposite. Maybe I don't have access? I can create branches on my computer, but not on the website. On the website, all I have is master.

**Comment by rigred** [comment]
I see you haven't got too much experience with git and github yet.
So as a one time offer to a new guy :smile_cat:  here's what you'll have to do:

Setup an SSH key on your github account and link it on your PC. 

1. Fork my repo (this you have already done)
2. Clone your own repo `git clone git@github.com:killerkalamari/sandsifter-tests.git`
3. Perform whatever changes on your local repo and stage the changed file `git add filename`
4.  Commit the file to 'your' fork `git commit -m 'message text here'`
5. Push your local changes to github `git push origin master`
6. Perform the Pull request between your fork and my repo

7. Learn git and github, I don't mean that in an offensive manner but the most friendly way. It will be really useful in future. 

The problems you are having probably stem from the fact that you seem to have clone my repo `github.com:rigred/sandsifter-tests.git` and are trying to push to it, instead of your own fork.

**Comment by killerkalamari** [comment]
I know git just fine, thanks for the insult. github != git

**Comment by zenware** [comment]
@killerkalamari If you are interested I will personally hold your hand through the process, you can [email me](mailto:jay.m.looney@gmail.com) and we could set up a skype call or whatever is convenient for you.

**Comment by killerkalamari** [comment]
@zenware Thanks for your kind offer. I've already created and checked out branches on my end, it just always gives me error 403 when I try to push. In the GitHub web interface it gives me no way that I can find to create a branch, but I can create me on my machine all day long of course. Here's an example of trying to push to a branch I created locally. But, the same thing happens if I try to push to master or to submissions.

```
~/sandsifter-tests>git push --set-upstream origin i7_4790k
remote: Permission to rigred/sandsifter-tests.git denied to killerkalamari.
fatal: unable to access 'https://github.com/rigred/sandsifter-tests.git/': The requested URL returned error: 403
```
![image](https://user-images.githubusercontent.com/5439104/31050960-914c107c-a610-11e7-9640-81741d0d4e90.png)

**Comment by killerkalamari** [comment]
@zenware I figured it out! The secret to creating a GitHub pull request is that you have to fork the repo, then you're allowed to push to your fork and create the pull request from your fork. Wasn't mentioned in the GitHub pull request docs.

**Comment by zenware** [comment]
@killerkalamari Congrats! It was mentioned by both myself and rigred in this very thread, could you help me figure out a better way to explain it so I don't struggle as much next time? (Perhaps over email in case rigred still has notifications enabled on this thread, I don't want to be a bother.) I'm also glad you figured it out, I want more people involved in open source software :)

**Comment by killerkalamari** [comment]
I tried to mention I hadn't forked earlier, everyone assumed I had, probably because it's second nature for those who were born on GitHub and equate git with GitHub as rigred does. Anyhow, forking was the crucial step. Forking is not a git operation, it seems to be a GitHub-only concept. I've used git for years at work, but only via file shares, ssh, Microsoft VSO, and the occasional personal GitHub repo that I created where I had full access. The way I stumbled onto the answer, was that I was honestly fed up and decided "fine I guess this fork thing lets me just copy the whole repo, I'll send them a link to the file and they can figure it out", and then I realized all the dialogs were now looking like the examples... ah well. I sent GitHub an email asking them to fix their docs (the one rigred linked didn't mention forking).

**Comment by rigred** [comment]
You really don't need to be so passive aggressive and assume for me as that I equate github with git.
I've been perfectly reasonable all this time. Do please understand that not everyone has the time to guide everyone through every trivial issue while also working on other priority projects.

I don't mean to offend in any way and only wish the best for everyone. Sorry If I've somehow come across as condescending. I apologize.

That aside I do think the github article could be updated to state starting assumptions such has having made a fork to create pull requests from. 

These are perhaps better articles: 

https://opensource.com/life/16/3/submit-github-pull-request

https://help.github.com/articles/creating-a-pull-request-from-a-fork/
